### PR TITLE
Removed Material UI Icon library

### PR DESCRIPTION
**Pull request by DaniG2106**

### CODE REVIEW

**Comment by phev8** [comment]
Looks good
There is one small issue in mobile view - it seems like the popup window is outside of the normal page view, and adds a horizontal scrolling effect to the page. Can that be handled differently?

Screenshot 2021-03-14 at 15 05 26

**Comment by phev8** [comment]
(This is not a new issue, the older version had similar problems... but maybe you can find a good way to solve this ;-) )

**Comment by DaniG2106** [comment]
Mhm interesting. I tested it on my phone (in Chrome) and the datepicker is then aligned to the right screen border, but nothing is outside of the view. Also when I zoom in, the datepicker tries to stay in the screen as long as possible until the zoomlevel is too large. How can I reproduce that problem?

**Comment by phev8** [comment]
In desktop chrome, it seemed to do this, what mentioned above. But if this is not issue on real devices, then it does not matter.

**Comment by DaniG2106** [comment]
The new AccordionList is automatically added to this pull request.

**Pull request merged**
